In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [16]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples=1000, n_features=10, n_redundant=5, n_informative=5, n_classes=2, random_state=1)


In [18]:
X.shape

(1000, 10)

In [43]:
y.shape

(1000,)

In [45]:
#Train_Test_Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=1)

In [47]:
#Hyperparameter tuning
#gridSearch CV 
#randomised search cv ...

In [49]:
#GridSearchCV
from sklearn.model_selection import GridSearchCV

params = {"penalty":('l1','l2','elasticnet'),'C':[1,2,10,20,30,40]}

In [51]:
params

{'penalty': ('l1', 'l2', 'elasticnet'), 'C': [1, 2, 10, 20, 30, 40]}

In [53]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression()

In [57]:
clf = GridSearchCV(classifier, param_grid=params,cv=5,verbose=2)
clf

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 10, 20, 30, 40],
                         'penalty': ('l1', 'l2', 'elasticnet')},
             verbose=2)

In [59]:
clf.fit(X_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ............................C=1, penalty=elasticnet; total time=   0.0s
[CV] END ............................C=1, penalt

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 10, 20, 30, 40],
                         'penalty': ('l1', 'l2', 'elasticnet')},
             verbose=2)

In [61]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [67]:
clf.best_score_

0.80625

In [63]:
clf.best_estimator_

LogisticRegression(C=1)

In [65]:
#now prediction two ways, directly predict from best estimator
clf.best_estimator_.predict(X_test)

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1])

In [69]:
model = LogisticRegression(C=1,penalty='l2')
model

LogisticRegression(C=1)

In [71]:
model.fit(X_train,y_train)

LogisticRegression(C=1)

In [75]:
y_pred = model.predict(X_test)
y_pred

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1])

In [79]:
model.predict_proba(X_test)

array([[0.01589785, 0.98410215],
       [0.84266072, 0.15733928],
       [0.70451437, 0.29548563],
       [0.86543984, 0.13456016],
       [0.4363369 , 0.5636631 ],
       [0.91047374, 0.08952626],
       [0.03392216, 0.96607784],
       [0.68783065, 0.31216935],
       [0.88083681, 0.11916319],
       [0.03768722, 0.96231278],
       [0.92471858, 0.07528142],
       [0.57431996, 0.42568004],
       [0.26644873, 0.73355127],
       [0.76243298, 0.23756702],
       [0.40880764, 0.59119236],
       [0.3155212 , 0.6844788 ],
       [0.04282863, 0.95717137],
       [0.13068134, 0.86931866],
       [0.02514161, 0.97485839],
       [0.93007644, 0.06992356],
       [0.54540378, 0.45459622],
       [0.03750493, 0.96249507],
       [0.18078577, 0.81921423],
       [0.90346854, 0.09653146],
       [0.08076816, 0.91923184],
       [0.44235007, 0.55764993],
       [0.85423236, 0.14576764],
       [0.53766208, 0.46233792],
       [0.50778359, 0.49221641],
       [0.83037355, 0.16962645],
       [0.

In [81]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[84 10]
 [25 81]]
0.825
              precision    recall  f1-score   support

           0       0.77      0.89      0.83        94
           1       0.89      0.76      0.82       106

    accuracy                           0.82       200
   macro avg       0.83      0.83      0.82       200
weighted avg       0.83      0.82      0.82       200



In [87]:
#Randomised search cv >> it will take randomaly some conmbination

from sklearn.model_selection import RandomizedSearchCV
randomized_clf = RandomizedSearchCV(classifier, param_distributions=params,n_iter =10,cv=5)

In [89]:
randomized_clf

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 2, 10, 20, 30, 40],
                                        'penalty': ('l1', 'l2', 'elasticnet')})

In [91]:
randomized_clf.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 2, 10, 20, 30, 40],
                                        'penalty': ('l1', 'l2', 'elasticnet')})

In [93]:
randomized_clf.best_score_

0.80625

In [101]:
randomized_clf.best_params_

{'penalty': 'l2', 'C': 10}

In [103]:
#builf ml model with these params
#or simply use best estimator